# Generated by Django 4.2.9 on 2024-01-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_subscription_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscriptionid',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
