# Generated by Django 4.2.9 on 2024-01-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_subscription_subscriptionid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscriptionid',
            field=models.CharField(default=1, max_length=70, unique=True),
            preserve_default=False,
        ),
    ]
