# Generated by Django 4.2.9 on 2024-01-25 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_subscription_subscriptionid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='user',
        ),
        migrations.RemoveField(
            model_name='word',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='subscribed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='subscriptionid',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='usage_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='word_limit',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='word_number',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='FreeServiceUsage',
        ),
        migrations.DeleteModel(
            name='Subscription',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
