# Generated by Django 4.2.9 on 2024-01-25 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_user_city_user_companyname_user_country_user_dni_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='subscriptioncancel',
            field=models.BooleanField(blank=True, default=1),
            preserve_default=False,
        ),
    ]
